---
abstract: 'Configuration, Error-handling, Localization, and Logging'
author:
  - 'Smithfarm <presnypreklad@gmail.com>'
build_requires:
  Log::Any::Test: 0
configure_requires:
  Module::Build: 0.37
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CELL
provides:
  App::CELL:
    file: lib/App/CELL.pm
    version: 0.124
  App::CELL::Config:
    file: lib/App/CELL/Config.pm
    version: 0.124
  App::CELL::Guide:
    file: lib/App/CELL/Guide.pm
    version: 0.124
  App::CELL::Load:
    file: lib/App/CELL/Load.pm
    version: 0.124
  App::CELL::Log:
    file: lib/App/CELL/Log.pm
    version: 0.124
  App::CELL::Message:
    file: lib/App/CELL/Message.pm
    version: 0.124
  App::CELL::Status:
    file: lib/App/CELL/Status.pm
    version: 0.124
  App::CELL::Test:
    file: lib/App/CELL/Test.pm
    version: 0.124
  App::CELL::Util:
    file: lib/App/CELL/Util.pm
    version: 0.124
requires:
  Date::Format: 0
  File::HomeDir: 0
  File::Next: 0
  File::ShareDir: 1.00
  File::Touch: 0
  Log::Any: 0
  Try::Tiny: 0
resources:
  license: http://www.gnu.org/licenses/gpl-3.0.txt
version: 0.124
